<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink()
        ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css')
        ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css')
        ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css')
    ?>

    <?= $this->headScript() ?>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                Skeleton app
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?= $this->url('home') ?>">Front</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <?= $this->content ?>

    <hr>
    <footer>
        <p>&copy; 2015 - <?= date('Y') ?> <a href="http://dotcom.software">Michal Zukowski</a> | thanks to Zend Technologies Ltd&reg;</p>
    </footer>
</div>

<?= $this->inlineScript()
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js')
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js')
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js')
?>

<script>
    (function () {
        $('.<?= \App\Form\Element\Select2::CLASS_NAME ?>').select2({theme: 'bootstrap'});
    })();
</script>
</body>
</html>