<?php
/** @var \App\Front\IntroductionForm $form */
$form = $this->form->prepare();
?>

<form method="post" action="">
    <?= $this->formElement($form->get('csrf')) ?>

    <h2>User</h2>
    <?= $this->formRow($form->get('user')->get('person')->get('firstName')) ?>
    <?= $this->formRow($form->get('user')->get('person')->get('lastName')) ?>
    <?= $this->formRow($form->get('user')->get('email')) ?>
    <?= $this->formRow($form->get('user')->get('language')) ?>
    <?= $this->formRow($form->get('user')->get('sex')) ?>

    <button class="btn btn-primary">Submit!</button>
</form>

<?php if ($form->hasValidated()): ?>
    <hr>

    <div class="alert alert-<?= $form->isValid() ? 'info': 'danger' ?>">
        <p>Is valid: <?= $form->isValid() ? 'yes': 'no' ?></p>
    </div>

    <?php if ($form->isValid()): ?>
        <pre><?php print_r($form->getData()) ?></pre>
    <?php endif ?>
<?php endif ?>
