<?php
/** @var \App\Front\IntroductionForm $form */
$form = $this->form->prepare();
?>

<p>The form:</p>

<form method="post" action="">
    <?= $this->formCollection($form) ?>
    <button>Submit!</button>
</form>

<?php if ($form->hasValidated()): ?>
    <hr>
    <p>Is valid: <?= $form->isValid() ? 'yes': 'no' ?></p>

    <?php if ($form->isValid()): ?>
        <pre><?php print_r($form->getData()) ?></pre>
    <?php endif ?>
<?php endif ?>
